versions
version224: spec
	<version: '2.2.4' imports: #('2.2.2-baseline' )>

	spec for: #'common' do: [
		spec blessing: #'development'.
		spec description: '* updated help
* categorized methods'.
		spec author: 'MaxLeske'.
		spec timestamp: '8/25/2011 19:44'.
		spec repository: 'http://www.squeaksource.com/FSGit'.
		spec project: 'Filesystem' with: '2.0.3'.
		spec package: 'FS-Git' with: 'FS-Git-MaxLeske.158'. ].
